### ISSUE TITLE
autocomplete not working

### ISSUE THREAD

**Issue by rcmoutinho** [brbsix/vagrant-bash-completion#3]
using the old and not anymore maintained autocomplete version, I have no problem

when I tried to switch to the new version I'm getting this error pressing TAB at any time
```
$ vagrant -bash: readarray: command not found
-bash: readarray: command not found
```

any suggestions? (I'm using OSX)
thanks

**Comment by rcmoutinho** [comment]
I'm also getting nothing from this URL (using `curl` command)
```
https://raw.github.com/brbsix/vagrant-bash-completion/master/vagrant-bash-completion/etc/bash_completion.d/vagrant
```

Maybe it is better changing for this URL
```
https://raw.githubusercontent.com/brbsix/vagrant-bash-completion/master/vagrant-bash-completion/etc/bash_completion.d/vagrant
```

**Comment by 0cjs** [comment]
The `readarray` (also known as [`mapfile`](http://wiki.bash-hackers.org/commands/builtin/mapfile)) command is available only in Bash 4, and MacOS ships with Bash 3. Probably the correct solution is to rewrite the code to use a [different method of reading the lines into an array](https://mywiki.wooledge.org/BashFAQ/001).

It would also be good to have a test framework that runs this under Bash 3. I do this with [dot-home](https://github.com/dot-home/_dot-home); have a look at the [`-3` option to its `Test` script](https://github.com/dot-home/_dot-home/blob/master/Test#L97-L101) to see how I handle this. (I download and build the MacOS `sed` as well because I use that too, but that's not necessary here.)

**Comment by rcmoutinho** [comment]
well done @0cjs !! it was the bash version, thanks !!
now it is working fine the autocomplete

PS.: for OSX users who want to update bash version:
- `brew install bash`
- Terminal > Preferences > General > Shells open with
  - `/usr/local/Cellar/bash/4.4.19/bin/bash` (take the version from brew output installation)
